POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Gazua",
    "email": "keymaster@familia.com",
    "password": "foreveralone",
    "role": "NORMAL"
}

###
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "keymaster@familia.com",
    "password": "foreveralone"
}

###
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiYmJhNDM1YjEtOTBiZC00M2MzLWI1YzYtNGUxMjEzMzBjZTIxIiwiaWF0IjoxNjM0OTQ4MzEyLCJleHAiOjE2MzQ5ODQzMTJ9.cBeJrytXQzOmXsNEq6TVouf8wiAQRqPSQbJHE2N8VBY

{
    "title": "teste",
    "description": "teste"
}

###
GET http://localhost:3003/user/7a85db86-b924-4857-b735-64ec478d6d07
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiN2E4NWRiODYtYjkyNC00ODU3LWI3MzUtNjRlYzQ3OGQ2ZDA3IiwiaWF0IjoxNjM0OTYyMzY2LCJleHAiOjE2MzQ5OTgzNjZ9.JBc0xwJXoTlMwt2e2l8A7IPXX8UI0sjlNQc0dUsgnc0

###
get http://localhost:3003/recipe/b776aff8-cf48-4b9a-a02a-866a664f7168
Authorization: sInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiYzhiNjY0MGYtY2ZlMi00ODE5LThmMjUtNzlmY2UyZWUwMTEyIiwiaWF0IjoxNjM0OTMwNTQ3LCJleHAiOjE2MzQ5NjY1NDd9.y3f3cCLeSSbf8S06hkwj2u_YiiF_Smx90aA7Lg-lBzI

###
post http://localhost:3003/follow/bba435b1-90bd-43c3-b5c6-4e121330ce21
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiN2E4NWRiODYtYjkyNC00ODU3LWI3MzUtNjRlYzQ3OGQ2ZDA3IiwiaWF0IjoxNjM0OTU4NDM5LCJleHAiOjE2MzQ5OTQ0Mzl9.om9nlMlUyitz39HYlFKTxDAA9Ajki5ATOtm_FvZaFb4


###
DELETE  http://localhost:3003/unfollow/7a85db86-b924-4857-b735-64ec478d6d07
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiN2E4NWRiODYtYjkyNC00ODU3LWI3MzUtNjRlYzQ3OGQ2ZDA3IiwiaWF0IjoxNjM0OTYwNjM5LCJleHAiOjE2MzQ5OTY2Mzl9.8-9vUETcL3XAhnAj0R0aBKO_GIoR7WnZysfgx6TAFCA

###
GET http://localhost:3003/feed
Authorization: .eyJwYXlsb2FkIjoiZGZiZGVlMDItNjBkMi00NWNmLWEwYTUtYmE2ZGQ5MjFmNzRhIiwiaWF0IjoxNjM0OTQzMDExLCJleHAiOjE2MzQ5NzkwMTF9.5XU2xwo0VVse92YDJy3VF_xwAuAxnOmV097kST6-oIQ

###
PUT http://localhost:3003/editrecipe/34892ea4-67e7-4f59-9fa8-c3eb938a4817
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiYmJhNDM1YjEtOTBiZC00M2MzLWI1YzYtNGUxMjEzMzBjZTIxIiwiaWF0IjoxNjM0OTUzMzA3LCJleHAiOjE2MzQ5ODkzMDd9.QMKq9I-yAY7x_qQVMHtScYzHucleozD8zqSqqMC0_RY

{
    "title": "Danete caseiro",
    "description": "lorem ipsum"
}
